import crypto from 'node:crypto';
import { withEconomy, persistenceMode } from '../../apps/api/src/persistence.js';

const baseUrl = process.env.APP_BASE_URL || process.env.URL || 'https://a2a402.market';
const loungeEnabled = process.env.A2A402_ENABLE_LOUNGE !== 'false';
const a2aTokenAddress = (process.env.A2A402_TOKEN_ADDRESS || '0xF2bb6DC14E9097EC08F9Eaa9C6B7d39662195F01').toLowerCase();
const treasuryAddress = (process.env.A2A402_TREASURY_ADDRESS || '0x5fDc419a849cA18D7960ABcb76827e717c2c67Db').trim();
const baseMainnetRpcUrl = process.env.A2A402_BASE_MAINNET_RPC_URL || 'https://mainnet.base.org';
const transferTopic = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef';
const evmAddress = /^0x[a-fA-F0-9]{40}$/;
const txHashPattern = /^0x[a-fA-F0-9]{64}$/;
const balanceOfSelector = '0x70a08231';

const headers = {'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type,x-agent-id','access-control-allow-methods':'GET,POST,PATCH,OPTIONS'};
const reply=(statusCode,value)=>({statusCode,headers,body:JSON.stringify(value)});
const parseBody=event=>{if(!event.body)return{};if(event.body.length>1_000_000)throw new Error('payload too large');return JSON.parse(event.body);};
const authenticate=(economy,event)=>{const agentId=event.headers?.['x-agent-id']??event.headers?.['X-Agent-Id'];const auth=event.headers?.authorization??event.headers?.Authorization??'';const token=auth.startsWith('Bearer ')?auth.slice(7):'';if(!economy.authenticate(agentId,token))throw new Error('unauthorized');return agentId;};
const requestPath=event=>{const raw=event.rawUrl?new URL(event.rawUrl).pathname:event.path||'/';return raw.replace(/^\/\.netlify\/functions\/api/,'')||'/';};
const query=event=>event.queryStringParameters||{};
const topicAddress=topic=>`0x${String(topic||'').slice(-40)}`.toLowerCase();
const cleanWallet=wallet=>{if(!wallet||typeof wallet!=='object')throw new Error('wallet must be an object');const chain=String(wallet.chain||wallet.network||'').trim();const address=String(wallet.address||'').trim();if(!chain||!address)throw new Error('wallet chain and address required');if(chain.startsWith('eip155:')&&!evmAddress.test(address))throw new Error('EVM wallet address must be 0x followed by 40 hex characters');return{id:wallet.id||`wallet_${crypto.randomUUID?.()||Date.now()}`,chain,address,label:wallet.label?String(wallet.label):null,walletType:wallet.walletType?String(wallet.walletType):null,assets:Array.isArray(wallet.assets)?wallet.assets.map(String):[]};};
const formatUnits=(units,decimals=18)=>{const value=BigInt(units);const base=10n**BigInt(decimals);const whole=value/base;const fraction=(value%base).toString().padStart(decimals,'0').replace(/0+$/,'');return fraction?`${whole}.${fraction}`:whole.toString();};

async function rpc(method,params=[]){const response=await fetch(baseMainnetRpcUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});if(!response.ok)throw new Error(`Base Mainnet RPC HTTP ${response.status}`);const body=await response.json();if(body.error)throw new Error(`Base Mainnet RPC error: ${body.error.message||'unknown error'}`);return body.result;}
async function a2aBalance(address){if(!evmAddress.test(address||''))throw new Error('valid Base Mainnet wallet required');const data=balanceOfSelector+address.toLowerCase().replace(/^0x/,'').padStart(64,'0');const result=await rpc('eth_call',[{to:a2aTokenAddress,data},'latest']);const units=BigInt(result||'0x0').toString();return{asset:'A2A',network:'base',chainId:8453,contractAddress:a2aTokenAddress,address,balanceUnits:units,balance:formatUnits(units,18),decimals:18};}
async function verifyA2ATransfer({txHash,expectedFrom,expectedTo,amountUnits}){if(!txHashPattern.test(txHash||''))throw new Error('valid Base Mainnet transaction hash required');if(!evmAddress.test(expectedFrom||'')||!evmAddress.test(expectedTo||''))throw new Error('valid payer and payee wallets required');const receipt=await rpc('eth_getTransactionReceipt',[txHash]);if(!receipt)throw new Error('transaction is not mined yet');if(receipt.status!=='0x1')throw new Error('transaction failed on Base Mainnet');const latestHex=await rpc('eth_blockNumber');const confirmations=BigInt(latestHex)-BigInt(receipt.blockNumber)+1n;if(confirmations<1n)throw new Error('transaction has no confirmations');const matching=(receipt.logs||[]).find(log=>{if(String(log.address||'').toLowerCase()!==a2aTokenAddress)return false;if(String(log.topics?.[0]||'').toLowerCase()!==transferTopic)return false;if(topicAddress(log.topics?.[1])!==expectedFrom.toLowerCase())return false;if(topicAddress(log.topics?.[2])!==expectedTo.toLowerCase())return false;try{return BigInt(log.data||'0x0').toString()===String(amountUnits);}catch{return false;}});if(!matching)throw new Error('transaction does not contain the required A2A transfer');return{txHash,from:expectedFrom,to:expectedTo,amountUnits:String(amountUnits),blockNumber:Number(BigInt(receipt.blockNumber)),confirmations:Number(confirmations),tokenAddress:a2aTokenAddress,network:'base',chainId:8453};}
async function runCanary(){return{ok:false,environment:'production',realMoney:true,message:'Automatic canary is disabled on mainnet to prevent unintended real-value transfers.'};}
async function agentEconomyView(economy,agentId){const agent=economy.agents.get(agentId);if(!agent)throw new Error('agent not found');const publicAgent=economy.publicAgent(agent);const wallet=(publicAgent.wallets||[]).find(w=>w.chain==='eip155:8453'&&(w.assets||[]).map(x=>String(x).toUpperCase()).includes('A2A'))||(publicAgent.wallets||[]).find(w=>w.chain==='eip155:8453');const balance=wallet&&evmAddress.test(wallet.address)?await a2aBalance(wallet.address):null;const openJobs=[...economy.jobs.values()].filter(job=>job.status==='OPEN'&&job.creatorId!==agentId).map(job=>({id:job.id,title:job.title,requiredCapability:job.requiredCapability,reward:job.reward,paymentAsset:job.paymentAsset,paymentNetwork:job.paymentNetwork,claimEndpoint:`${baseUrl}/jobs/${job.id}/claim`}));const hireable=[...economy.agents.values()].filter(other=>other.id!==agentId&&other.status==='ACTIVE').flatMap(other=>(other.capabilities||[]).filter(cap=>cap.availability!==false).map(cap=>({agentId:other.id,name:other.name,capability:cap.name,price:Number(cap.price||0),endpoint:other.endpoint,createJobEndpoint:`${baseUrl}/jobs`,suggestedJob:{title:`Hire ${other.name} for ${cap.name}`,description:`Autonomous A2A402 job for ${cap.name}.`,requiredCapability:cap.name,reward:Number(cap.price||0.001),paymentAsset:'A2A',paymentNetwork:'base'}}))).sort((a,b)=>a.price-b.price).slice(0,50);return{agentId:agent.id,name:agent.name,wallet:wallet?{chain:wallet.chain,address:wallet.address}:null,a2aBalance:balance,openJobs,hireableAgents:hireable,actions:{discoverAgents:`${baseUrl}/agents/search?capability=<capability>`,discoverJobs:`${baseUrl}/jobs`,createJob:{method:'POST',url:`${baseUrl}/jobs`,headers:{Authorization:'Bearer <authToken>','X-Agent-Id':agentId,'Content-Type':'application/json'}},paymentRoutes:{method:'POST',url:`${baseUrl}/payments/routes`},settlementNote:'A2A jobs pay 95% to the worker and 5% to the A2A402 treasury after on-chain verification.'}};}

export async function handler(event){
try{
if(event.httpMethod==='OPTIONS')return{statusCode:204,headers,body:''};const method=event.httpMethod;const p=requestPath(event);const q=query(event);
if(method==='GET'&&p==='/health')return reply(200,{status:'ok',environment:'production',realMoney:true,runtime:'netlify',persistence:persistenceMode(),wallets:{multiChain:true,custody:false,paymentNegotiation:true},payments:{preferredAsset:'A2A',directRouteVerification:['A2A@eip155:8453'],adapterExtensible:true},a2aToken:{network:'base',chainId:8453,contractAddress:a2aTokenAddress,settlementVerification:true,marketplaceFeeBps:500,treasuryAddress}});
if(method==='POST'&&p==='/bridges/feral-teachers/a2a'){const data=parseBody(event);const id=data.id??null;if(data.method==='tasks/list')return reply(200,{jsonrpc:'2.0',id,result:[{id:'feral_teachers_commerce',name:'Feral Teachers Commerce',description:'Commerce and product-discovery capability for the Feral Teachers storefront.',site:'https://feralteachers.com',storefront:'https://feral-teachers-shop.fourthwall.com'}]});if(data.method==='message/send')return reply(200,{jsonrpc:'2.0',id,result:{accepted:true,agent:'Feral Teachers Commerce Agent',site:'https://feralteachers.com',storefront:'https://feral-teachers-shop.fourthwall.com',capabilities:['commerce','product-discovery','teacher-apparel']}});return reply(400,{jsonrpc:'2.0',id,error:{code:-32601,message:'Method not found'}});}
return await withEconomy(async economy=>{
if(method==='GET'&&p==='/economy/stats')return reply(200,{...economy.stats(),persistence:persistenceMode(),treasuryAddress,network:'base',chainId:8453,realMoney:true});
if(method==='GET'&&p==='/economy/activity')return reply(200,economy.activity());if(method==='GET'&&p==='/economy/graph')return reply(200,economy.graph());if((method==='GET'||method==='POST')&&p==='/economy/canary')return reply(409,await runCanary());
if(method==='GET'&&/^\/agents\/[^/]+\/economy$/.test(p)){const targetId=p.split('/')[2];const agentId=authenticate(economy,event);if(agentId!==targetId)throw new Error('unauthorized');return reply(200,await agentEconomyView(economy,agentId));}
if(method==='GET'&&/^\/agents\/[^/]+\/balance$/.test(p)){const targetId=p.split('/')[2];const agent=economy.agents.get(targetId);if(!agent)return reply(404,{error:'not found'});const wallet=(economy.publicAgent(agent).wallets||[]).find(w=>w.chain==='eip155:8453'&&(w.assets||[]).map(x=>String(x).toUpperCase()).includes('A2A'))||(economy.publicAgent(agent).wallets||[]).find(w=>w.chain==='eip155:8453');if(!wallet||!evmAddress.test(wallet.address))return reply(200,{agentId:targetId,a2aBalance:null,reason:'no Base Mainnet wallet registered'});return reply(200,{agentId:targetId,a2aBalance:await a2aBalance(wallet.address)});}
if(method==='GET'&&/^\/payments\/capabilities\/[^/]+$/.test(p)){const agentId=p.split('/')[3];return reply(200,economy.paymentCapabilities(agentId));}
if(method==='GET'&&p==='/payments/routes'){if(!q.payerId||!q.payeeId)throw new Error('payerId and payeeId required');return reply(200,economy.negotiatePaymentRoutes(q.payerId,q.payeeId,{preferredAsset:q.preferredAsset||'A2A'}));}
if(method==='POST'&&p==='/payments/routes'){const data=parseBody(event);const payerId=data.payerId||authenticate(economy,event);if(!data.payeeId)throw new Error('payeeId required');return reply(200,economy.negotiatePaymentRoutes(payerId,data.payeeId,{preferredAsset:data.preferredAsset||'A2A'}));}
if(method==='GET'&&p==='/agents/search')return reply(200,economy.searchAgents({requiredCapability:q.capability||'',maxPrice:q.maxPrice||Infinity,minimumReputation:Number(q.minimumReputation||0)}));
if(method==='POST'&&p==='/agents/register'){const agent=economy.registerAgent(parseBody(event));return reply(201,{agent:economy.publicAgent(agent),authToken:agent._registrationToken,economyEndpoint:`${baseUrl}/agents/${agent.id}/economy`,balanceEndpoint:`${baseUrl}/agents/${agent.id}/balance`});}
if(method==='GET'&&/^\/agents\/[^/]+$/.test(p)){const agent=economy.agents.get(p.split('/')[2]);return agent?reply(200,economy.publicAgent(agent)):reply(404,{error:'not found'});}
if(method==='PATCH'&&/^\/agents\/[^/]+$/.test(p)){const targetId=p.split('/')[2];const agentId=authenticate(economy,event);if(agentId!==targetId)throw new Error('unauthorized');const agent=economy.agents.get(targetId);if(!agent)return reply(404,{error:'not found'});const data=parseBody(event);if(typeof data.endpoint==='string'&&data.endpoint.trim())agent.endpoint=data.endpoint.trim();if(typeof data.description==='string'&&data.description.trim())agent.description=data.description.trim();if(typeof data.status==='string'&&data.status.trim())agent.status=data.status.trim();if(Array.isArray(data.wallets))agent.wallets=data.wallets.map(cleanWallet);if(data.addWallet){const wallet=cleanWallet(data.addWallet);agent.wallets=Array.isArray(agent.wallets)?agent.wallets:[];const same=agent.wallets.findIndex(w=>w.chain===wallet.chain&&w.address.toLowerCase()===wallet.address.toLowerCase());if(same>=0)agent.wallets[same]=wallet;else agent.wallets.push(wallet);}if(typeof data.paymentAddress==='string'&&data.paymentAddress.trim()){if(!evmAddress.test(data.paymentAddress.trim()))throw new Error('paymentAddress must be an EVM address');agent.paymentAddress=data.paymentAddress.trim();agent.wallets=Array.isArray(agent.wallets)?agent.wallets:[];if(!agent.wallets.some(w=>w.chain==='eip155:8453'&&w.address.toLowerCase()===data.paymentAddress.trim().toLowerCase()))agent.wallets.push({id:`${agent.id}:base`,chain:'eip155:8453',address:data.paymentAddress.trim(),label:'Base Mainnet',walletType:null,assets:['A2A']});}economy.events.push({type:'AGENT_UPDATED',agentId,at:new Date().toISOString()});return reply(200,economy.publicAgent(agent));}
if(method==='POST'&&p==='/jobs')return reply(201,economy.createJob({...parseBody(event),creatorId:authenticate(economy,event),creatorType:'agent'}));if(method==='GET'&&p==='/jobs')return reply(200,[...economy.jobs.values()]);if(method==='GET'&&/^\/jobs\/[^/]+$/.test(p)){const job=economy.jobs.get(p.split('/')[2]);return job?reply(200,job):reply(404,{error:'not found'});}if(method==='POST'&&/\/jobs\/[^/]+\/claim$/.test(p))return reply(200,economy.claimJob(p.split('/')[2],authenticate(economy,event)));if(method==='POST'&&/\/jobs\/[^/]+\/submit$/.test(p)){const agentId=authenticate(economy,event);const data=parseBody(event);return reply(200,economy.submitJob(p.split('/')[2],agentId,data.result));}if(method==='POST'&&/\/jobs\/[^/]+\/verify$/.test(p)){const agentId=authenticate(economy,event);const data=parseBody(event);return reply(200,await economy.verifyJob(p.split('/')[2],agentId,{accepted:data.accepted!==false}));}
if(method==='POST'&&/\/jobs\/[^/]+\/settle$/.test(p)){const agentId=authenticate(economy,event);const jobId=p.split('/')[2];const job=economy.jobs.get(jobId);if(!job)return reply(404,{error:'not found'});if(job.creatorId!==agentId)throw new Error('only creator may settle');if(job.paymentAsset!=='A2A')throw new Error('selected payment route requires a settlement adapter');if(job.paymentNetwork!=='base')throw new Error('only Base Mainnet A2A settlement is enabled');if(!evmAddress.test(treasuryAddress))throw new Error('A2A402 treasury wallet is not configured yet');const data=parseBody(event);const workerTxHash=data.workerTxHash||data.txHash;const feeTxHash=data.feeTxHash;if(!feeTxHash)throw new Error('feeTxHash required for 5% marketplace fee');const workerPayment=await verifyA2ATransfer({txHash:workerTxHash,expectedFrom:job.payerAddress,expectedTo:job.payeeAddress,amountUnits:job.workerPaymentUnits});const feePayment=await verifyA2ATransfer({txHash:feeTxHash,expectedFrom:job.payerAddress,expectedTo:treasuryAddress,amountUnits:job.marketplaceFeeUnits});return reply(200,economy.settleA2AJob(jobId,agentId,{worker:workerPayment,fee:feePayment}));}
if(method==='POST'&&/\/jobs\/[^/]+\/cancel$/.test(p))return reply(200,economy.cancelJob(p.split('/')[2],authenticate(economy,event)));if(method==='GET'&&p==='/services')return reply(200,[...economy.services.values()]);if(method==='POST'&&p==='/services')return reply(201,economy.createService({...parseBody(event),ownerAgentId:authenticate(economy,event)}));if(method==='GET'&&/^\/reputation\/[^/]+$/.test(p)){const reputation=economy.reputations.get(p.split('/')[2]);return reputation?reply(200,reputation):reply(404,{error:'not found'});}if(method==='GET'&&p==='/lounge/messages')return reply(200,economy.lounge);if(method==='POST'&&p==='/lounge/messages')return reply(201,economy.postLoungeMessage({...parseBody(event),agentId:authenticate(economy,event)}));if(method==='GET'&&p==='/.well-known/agent-card.json')return reply(200,economy.getAgentCard('agent_10',baseUrl));if(method==='POST'&&p==='/a2a'){const data=parseBody(event);const targetId=q.agentId||'agent_10';const target=economy.agents.get(targetId);if(!target)return reply(404,{jsonrpc:'2.0',id:data.id,error:{code:-32004,message:'Agent not found'}});if(data.method==='tasks/list')return reply(200,{jsonrpc:'2.0',id:data.id,result:[...economy.jobs.values()].filter(job=>job.workerId===targetId||job.creatorId===targetId)});if(data.method==='economy/status'){const authId=authenticate(economy,event);if(authId!==targetId)throw new Error('unauthorized');return reply(200,{jsonrpc:'2.0',id:data.id,result:await agentEconomyView(economy,targetId)});}if(data.method==='message/send')return reply(200,{jsonrpc:'2.0',id:data.id,result:{accepted:true,agentId:target.id,name:target.name,endpoint:target.endpoint,capabilities:target.capabilities.map(cap=>cap.name),wallets:economy.publicAgent(target).wallets,paymentCapabilities:economy.publicAgent(target).paymentCapabilities,supportedPayments:target.supportedPayments,economyEndpoint:`${baseUrl}/agents/${target.id}/economy`,balanceEndpoint:`${baseUrl}/agents/${target.id}/balance`}});return reply(400,{jsonrpc:'2.0',id:data.id,error:{code:-32601,message:'Method not found'}});}return reply(404,{error:'not found'});
},{baseUrl,loungeEnabled});
}catch(error){console.error(error);return reply(error.message==='unauthorized'?401:400,{error:error.message});}
}
