import { withEconomy } from '../../apps/api/src/persistence.js';
import { founderProgram, founderRegistry, founderCandidates, founderCandidate, FOUNDER_GRANT_A2A, FOUNDER_COHORT_SIZE, FOUNDER_WALLET_ADDRESS } from '../../apps/api/src/founders.js';

const headers={'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'GET,POST,OPTIONS'};
const reply=(statusCode,value)=>({statusCode,headers,body:JSON.stringify(value)});
const token=(process.env.A2A402_TOKEN_ADDRESS||'0xF2bb6DC14E9097EC08F9Eaa9C6B7d39662195F01').toLowerCase();
const rpcUrl=process.env.A2A402_BASE_MAINNET_RPC_URL||'https://mainnet.base.org';
const founderWallet=(process.env.A2A402_FOUNDER_WALLET_ADDRESS||FOUNDER_WALLET_ADDRESS).trim();
const evm=/^0x[a-fA-F0-9]{40}$/;
const txHash=/^0x[a-fA-F0-9]{64}$/;
const transferTopic='0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef';
function pathOf(event){const raw=event.rawUrl?new URL(event.rawUrl).pathname:event.path||'/';return raw.replace(/^\/\.netlify\/functions\/founders/,'').replace(/^\/founder-program/,'')||'/'}
function body(event){return event.body?JSON.parse(event.body):{}}
function admin(event){const expected=process.env.A2A402_FOUNDER_ADMIN_TOKEN||'';const auth=event.headers?.authorization||event.headers?.Authorization||'';if(!expected||auth!==`Bearer ${expected}`)throw new Error('admin authorization required')}
async function rpc(method,params=[]){const r=await fetch(rpcUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});if(!r.ok)throw new Error(`Base RPC HTTP ${r.status}`);const j=await r.json();if(j.error)throw new Error(j.error.message||'Base RPC error');return j.result}
function unitsToDecimal(units){const v=BigInt(units),base=10n**18n,w=v/base,f=(v%base).toString().padStart(18,'0').replace(/0+$/,'');return f?`${w}.${f}`:w.toString()}
async function poolBalance(){if(!evm.test(founderWallet))throw new Error('Founder wallet not configured');const data='0x70a08231'+founderWallet.toLowerCase().slice(2).padStart(64,'0');const raw=await rpc('eth_call',[{to:token,data},'latest']);const units=BigInt(raw||'0x0');return{network:'base',chainId:8453,tokenContract:token,walletAddress:founderWallet,balanceUnits:units.toString(),balanceA2A:unitsToDecimal(units),targetAllocationA2A:100000,fullyFunded:units>=100000n*10n**18n,checkedAt:new Date().toISOString()}}
async function verifyGrantTx(hash,to){if(!txHash.test(hash||''))throw new Error('valid transaction hash required');if(!evm.test(to||''))throw new Error('valid recipient wallet required');const receipt=await rpc('eth_getTransactionReceipt',[hash]);if(!receipt||receipt.status!=='0x1')throw new Error('transaction not successfully mined');const expected=BigInt(FOUNDER_GRANT_A2A)*10n**18n;const match=(receipt.logs||[]).find(log=>String(log.address||'').toLowerCase()===token&&String(log.topics?.[0]||'').toLowerCase()===transferTopic&&`0x${String(log.topics?.[1]||'').slice(-40)}`.toLowerCase()===founderWallet.toLowerCase()&&`0x${String(log.topics?.[2]||'').slice(-40)}`.toLowerCase()===to.toLowerCase()&&BigInt(log.data||'0x0')===expected);if(!match)throw new Error('transaction does not contain the required 1,000 A2A Founder transfer');return{txHash:hash,recipient:to,amountA2A:FOUNDER_GRANT_A2A,blockNumber:Number(BigInt(receipt.blockNumber)),verifiedAt:new Date().toISOString()}}
export async function handler(event){try{if(event.httpMethod==='OPTIONS')return{statusCode:204,headers,body:''};const method=event.httpMethod,p=pathOf(event);return await withEconomy(async economy=>{
if(method==='GET'&&p==='/status'){const program=founderProgram(economy);let funding;try{funding=await poolBalance()}catch(e){funding={verified:false,error:e.message,walletAddress:founderWallet}}return reply(200,{...program,funding})}
if(method==='GET'&&p==='/balance')return reply(200,await poolBalance());
if(method==='GET'&&p==='/candidates')return reply(200,{count:founderCandidates(economy).length,candidates:founderCandidates(economy)});
if(method==='GET'&&p==='/registry')return reply(200,{count:founderRegistry(economy).length,founders:founderRegistry(economy)});
if(method==='GET'&&/^\/candidates\/[^/]+$/.test(p)){const id=p.split('/')[2],agent=economy.agents.get(id);return agent?reply(200,founderCandidate(economy,agent)):reply(404,{error:'agent not found'})}
if(method==='POST'&&p==='/approve'){admin(event);const data=body(event),agent=economy.agents.get(data.agentId);if(!agent)throw new Error('agent not found');const candidate=founderCandidate(economy,agent);if(!candidate.eligibleForReview)throw new Error('candidate has not completed Founder requirements');if(data.independentOperatorVerified!==true)throw new Error('independent operator verification required');economy.founders=Array.isArray(economy.founders)?economy.founders:[];if(economy.founders.some(f=>f.agentId===agent.id))throw new Error('agent already has Founder record');if(economy.founders.length>=FOUNDER_COHORT_SIZE)throw new Error('Founder cohort is full');const number=economy.founders.length+1,record={founderNumber:number,agentId:agent.id,name:agent.name,walletAddress:candidate.walletAddress,status:'APPROVED_AWAITING_GRANT',approvedAt:new Date().toISOString(),grantA2A:FOUNDER_GRANT_A2A,grantTxHash:null,grantedAt:null,qualification:candidate.participation,verificationNote:String(data.verificationNote||'').slice(0,500)};economy.founders.push(record);economy.event('FOUNDER_APPROVED',{agentId:agent.id,founderNumber:number});return reply(201,record)}
if(method==='POST'&&p==='/confirm-grant'){admin(event);const data=body(event);economy.founders=Array.isArray(economy.founders)?economy.founders:[];const record=economy.founders.find(f=>f.agentId===data.agentId);if(!record)throw new Error('Founder record not found');if(record.status==='GRANTED')throw new Error('Founder grant already recorded');const proof=await verifyGrantTx(data.txHash,record.walletAddress);record.status='GRANTED';record.grantTxHash=proof.txHash;record.grantedAt=new Date().toISOString();record.grantProof=proof;economy.event('FOUNDER_GRANTED',{agentId:record.agentId,founderNumber:record.founderNumber,txHash:proof.txHash});return reply(200,record)}
return reply(404,{error:'not found'});
});}catch(error){return reply(error.message==='admin authorization required'?401:400,{error:error.message})}}
