import test from 'node:test'; import assert from 'node:assert/strict';
import { Economy } from '../apps/api/src/economy.js'; import { registerSeeds } from '../apps/api/src/seed.js';
function setup(){const e=new Economy();const a=registerSeeds(e,{baseUrl:'https://a2a402.market'});for(const x of a)x.balance=1;return {e,a};}
test('agent registration and capability discovery',()=>{const {e}=setup();assert.equal(e.agents.size,10);const result=e.searchAgents({requiredCapability:'coding'});assert.equal(result.length,1);assert.equal(result[0].endpoint,'https://a2a402.market/a2a?agentId=agent_5');});
test('job creation and authorized claiming',()=>{const {e,a}=setup();const j=e.createJob({creatorId:a[9].id,title:'code',description:'x',requiredCapability:'coding',reward:.01});assert.throws(()=>e.claimJob(j.id,a[0].id));e.claimJob(j.id,a[4].id);assert.equal(j.status,'IN_PROGRESS');});
test('completion, payment, reputation, duplicate settlement protection',async()=>{const {e,a}=setup();const j=e.createJob({creatorId:a[9].id,title:'code',description:'x',requiredCapability:'coding',reward:.01});e.claimJob(j.id,a[4].id);e.submitJob(j.id,a[4].id,{ok:true});await e.verifyJob(j.id,a[9].id);assert.equal(j.status,'PAID');assert.equal(e.transactions.length,1);assert.equal(e.reputations.get(a[4].id).successfulJobs,1);await assert.rejects(()=>e.verifyJob(j.id,a[9].id));assert.equal(e.transactions.length,1);});
test('agent-created sub-job and graph relationship',()=>{const {e,a}=setup();const root=e.createJob({creatorId:a[9].id,creatorType:'human',title:'report',description:'x',requiredCapability:'research',reward:.01});e.claimJob(root.id,a[0].id);const sub=e.createJob({creatorId:a[0].id,creatorType:'agent',parentJobId:root.id,title:'translate',description:'x',requiredCapability:'translation.ja-en',reward:.003});assert.equal(sub.parentJobId,root.id);assert.ok(e.graph().edges.some(x=>x.from===root.id&&x.to===sub.id&&x.type==='spawned'));});
test('failed jobs update reputation',async()=>{const {e,a}=setup();const j=e.createJob({creatorId:a[9].id,title:'research',description:'x',requiredCapability:'research',reward:.01});e.claimJob(j.id,a[0].id);e.submitJob(j.id,a[0].id,{bad:true});await e.verifyJob(j.id,a[9].id,{accepted:false});assert.equal(j.status,'FAILED');assert.equal(e.reputations.get(a[0].id).failedJobs,1);});
test('lounge can be disabled without breaking economy',()=>{const e=new Economy({loungeEnabled:false});const a=registerSeeds(e,{baseUrl:'https://a2a402.market'});for(const x of a)x.balance=1;assert.throws(()=>e.postLoungeMessage({agentId:a[0].id,message:'hi'}));const j=e.createJob({creatorId:a[9].id,title:'r',description:'x',requiredCapability:'research',reward:.01});assert.equal(j.status,'OPEN');});
test('end-to-end multi-agent workflow',async()=>{const {e,a}=setup();const root=e.createJob({creatorId:a[9].id,creatorType:'human',title:'market report',description:'x',requiredCapability:'research',reward:.02});e.claimJob(root.id,a[0].id);const sub=e.createJob({creatorId:a[0].id,creatorType:'agent',parentJobId:root.id,title:'translate source',description:'x',requiredCapability:'translation.ja-en',reward:.003});e.claimJob(sub.id,a[2].id);e.submitJob(sub.id,a[2].id,{translation:'ok'});await e.verifyJob(sub.id,a[0].id);e.submitJob(root.id,a[0].id,{report:'ok'});await e.verifyJob(root.id,a[9].id);assert.equal(root.status,'PAID');assert.equal(sub.status,'PAID');assert.equal(e.transactions.length,2);assert.equal(e.stats().agentCreatedJobs,1);});
test('agent can register wallets on multiple chains',()=>{const e=new Economy();const agent=e.registerAgent({name:'Multi Wallet Agent',description:'uses several chains',endpoint:'https://example.com/a2a',capabilities:['research'],wallets:[{chain:'eip155:84532',address:'0x1111111111111111111111111111111111111111',walletType:'MetaMask',assets:['A2A']},{chain:'solana:mainnet',address:'So11111111111111111111111111111111111111112',walletType:'Phantom',assets:['SOL','USDC']},{chain:'bip122:bitcoin',address:'bc1qexampleaddress',walletType:'Bitcoin Core',assets:['BTC']}]});const pub=e.publicAgent(agent);assert.equal(pub.wallets.length,3);assert.equal(pub.wallets[1].chain,'solana:mainnet');assert.equal(pub.wallets[2].chain,'bip122:bitcoin');});
test('A2A token jobs select the Base Sepolia wallet from a multi-wallet profile',async()=>{const e=new Economy();const creator=e.registerAgent({name:'Creator',description:'creator',endpoint:'https://creator.example/a2a',capabilities:['broker'],wallets:[{chain:'solana:mainnet',address:'So11111111111111111111111111111111111111112'},{chain:'eip155:84532',address:'0x1111111111111111111111111111111111111111',assets:['A2A']}]});const worker=e.registerAgent({name:'Worker',description:'worker',endpoint:'https://worker.example/a2a',capabilities:['research'],wallets:[{chain:'bip122:bitcoin',address:'bc1qexample'},{chain:'eip155:84532',address:'0x2222222222222222222222222222222222222222',assets:['A2A']}]});const j=e.createJob({creatorId:creator.id,title:'token research',description:'x',requiredCapability:'research',reward:2,paymentAsset:'A2A',paymentNetwork:'base-sepolia'});assert.equal(j.payerAddress,'0x1111111111111111111111111111111111111111');e.claimJob(j.id,worker.id);assert.equal(j.payeeAddress,'0x2222222222222222222222222222222222222222');e.submitJob(j.id,worker.id,{ok:true});await e.verifyJob(j.id,creator.id);assert.equal(j.status,'AWAITING_PAYMENT');const settled=e.settleA2AJob(j.id,creator.id,{txHash:'0x'+'a'.repeat(64),from:j.payerAddress,to:j.payeeAddress,amountUnits:j.paymentAmountUnits,blockNumber:123});assert.equal(settled.job.status,'PAID');});
test('A2A token job creation rejects creator without Base Sepolia wallet',()=>{const e=new Economy();const creator=e.registerAgent({name:'Solana Only',description:'creator',endpoint:'https://example.com/a2a',capabilities:['broker'],wallets:[{chain:'solana:mainnet',address:'So11111111111111111111111111111111111111112'}]});assert.throws(()=>e.createJob({creatorId:creator.id,title:'token research',description:'x',requiredCapability:'research',reward:1,paymentAsset:'A2A',paymentNetwork:'base-sepolia'}),/Base Sepolia-compatible wallet/);});
