import crypto from 'node:crypto';
import { id, now, assert, normalizeCapability, agentCard } from '../../../packages/protocol/src/index.js';
import { MockTestProvider } from '../../../packages/payments/src/index.js';
import { emptyReputation, recordSuccess, recordFailure } from '../../../packages/reputation/src/index.js';

export class Economy {
  constructor({ paymentProvider = new MockTestProvider(), loungeEnabled = true } = {}) {
    this.paymentProvider = paymentProvider; this.loungeEnabled = loungeEnabled;
    this.agents = new Map(); this.jobs = new Map(); this.transactions = []; this.reputations = new Map(); this.services = new Map(); this.lounge = []; this.events = [];
  }
  event(type, data={}) { const e = { id: id('evt'), type, at: now(), ...data }; this.events.push(e); return e; }
  registerAgent(input) {
    assert(input?.name && input?.description && input?.endpoint, 'name, description, endpoint required');
    assert(Array.isArray(input.capabilities) && input.capabilities.length, 'capabilities required');
    const agentId = input.id ?? id('agent');
    const capabilities = input.capabilities.map((c,i) => typeof c === 'string' ? ({ id: `${agentId}:cap:${i}`, name: normalizeCapability(c), description: c, inputTypes:['application/json'], outputTypes:['application/json'], pricingModel:'fixed', price:0.001, providerAgent:agentId, availability:true }) : ({...c, name: normalizeCapability(c.name), providerAgent: agentId, availability: c.availability !== false }));
    const authToken = input.authToken ?? crypto.randomBytes(24).toString('base64url');
    const agent = { id: agentId, name: input.name, description: input.description, endpoint: input.endpoint, capabilities, paymentAddress: input.paymentAddress ?? `test:${agentId}`, supportedPayments: input.supportedPayments ?? [{network:'eip155:84532',asset:'USDC_TEST'}], status:'ACTIVE', createdAt: now(), balance: Number(input.balance ?? 0), authTokenHash: crypto.createHash('sha256').update(authToken).digest('hex') };
    Object.defineProperty(agent, '_registrationToken', { value: authToken, enumerable: false, writable: false });
    this.agents.set(agent.id, agent); this.reputations.set(agent.id, emptyReputation(agent.id)); this.event('AGENT_REGISTERED',{agentId:agent.id}); return agent;
  }
  authenticate(agentId, token) { const agent=this.agents.get(agentId); if(!agent||!token)return false; const hash=crypto.createHash('sha256').update(token).digest('hex'); try{return crypto.timingSafeEqual(Buffer.from(hash),Buffer.from(agent.authTokenHash));}catch{return false;} }
  publicAgent(agent) { if(!agent)return null; const { authTokenHash, ...safe }=agent; return safe; }
  searchAgents({ requiredCapability, maxPrice = Infinity, minimumReputation = 0 }={}) {
    const cap = normalizeCapability(requiredCapability);
    return [...this.agents.values()].map(agent => ({ agent: this.publicAgent(agent), capability: agent.capabilities.find(c => c.name === cap && c.availability && Number(c.price)<=Number(maxPrice)), reputation: this.reputations.get(agent.id) })).filter(x => x.agent.status==='ACTIVE' && x.capability && x.reputation.successRate >= minimumReputation).sort((a,b) => Number(a.capability.price)-Number(b.capability.price) || b.reputation.successRate-a.reputation.successRate).map(x => ({agentId:x.agent.id,name:x.agent.name,endpoint:x.agent.endpoint,capability:x.capability,reputation:x.reputation}));
  }
  createJob(input) {
    assert(input?.creatorId && this.agents.has(input.creatorId), 'valid creatorId required'); assert(input?.title && input?.description && input?.requiredCapability, 'title, description, requiredCapability required'); assert(Number(input.reward)>0, 'reward must be positive');
    const parent = input.parentJobId ? this.jobs.get(input.parentJobId) : null; if (input.parentJobId) assert(parent, 'parentJobId not found');
    const job = { id:id('job'), creatorId:input.creatorId, creatorType:input.creatorType ?? 'agent', title:input.title, description:input.description, input:input.input ?? {}, requiredCapability:normalizeCapability(input.requiredCapability), reward:Number(input.reward), paymentAsset:input.paymentAsset ?? 'USDC_TEST', paymentNetwork:input.paymentNetwork ?? 'base-sepolia', deadline:input.deadline ?? new Date(Date.now()+3600000).toISOString(), verificationMethod:input.verificationMethod ?? 'deterministic', status:'OPEN', workerId:null, result:null, parentJobId:input.parentJobId ?? null, rootJobId:parent?.rootJobId ?? parent?.id ?? null, spawnedByJobId:input.spawnedByJobId ?? input.parentJobId ?? null, createdAt:now(), updatedAt:now(), claimedAt:null, submittedAt:null, completedAt:null };
    this.jobs.set(job.id, job); this.event('JOB_CREATED',{jobId:job.id,creatorId:job.creatorId,parentJobId:job.parentJobId}); return job;
  }
  claimJob(jobId, agentId) { const job=this.jobs.get(jobId); assert(job,'job not found'); assert(job.status==='OPEN','job not open'); assert(agentId!==job.creatorId,'creator cannot claim own job'); const agent=this.agents.get(agentId); assert(agent,'agent not found'); assert(agent.capabilities.some(c=>c.name===job.requiredCapability && c.availability),'agent lacks capability'); job.workerId=agentId; job.status='IN_PROGRESS'; job.claimedAt=now(); job.updatedAt=now(); this.event('JOB_CLAIMED',{jobId,agentId}); return job; }
  submitJob(jobId, agentId, result) { const job=this.jobs.get(jobId); assert(job,'job not found'); assert(job.workerId===agentId,'only worker may submit'); assert(job.status==='IN_PROGRESS','job not in progress'); job.result=result; job.status='SUBMITTED'; job.submittedAt=now(); job.updatedAt=now(); this.event('JOB_SUBMITTED',{jobId,agentId}); return job; }
  async verifyJob(jobId, creatorId, { accepted=true }={}) { const job=this.jobs.get(jobId); assert(job,'job not found'); assert(job.creatorId===creatorId,'only creator may verify'); assert(job.status==='SUBMITTED','job not submitted'); job.status='VERIFYING'; if (!accepted) { job.status='FAILED'; recordFailure(this.reputations.get(job.workerId),{capability:job.requiredCapability}); this.event('JOB_FAILED',{jobId}); return job; }
    job.status='COMPLETED'; job.completedAt=now(); const worker=this.agents.get(job.workerId); const creator=this.agents.get(job.creatorId); assert(creator.balance >= job.reward, 'creator has insufficient simulated balance'); const tx=await this.paymentProvider.settle({idempotencyKey:`job:${job.id}:settlement`,jobId:job.id,payer:creator.id,payee:worker.id,amount:job.reward,asset:job.paymentAsset,network:job.paymentNetwork}); if (!this.transactions.find(t=>t.id===tx.id)) { creator.balance-=job.reward; worker.balance+=job.reward; this.transactions.push(tx); recordSuccess(this.reputations.get(worker.id),{capability:job.requiredCapability,amount:job.reward,durationMs:Math.max(1,new Date(job.completedAt)-new Date(job.claimedAt)),customerId:creator.id}); }
    job.status='PAID'; job.updatedAt=now(); this.event('JOB_PAID',{jobId,transactionId:tx.id}); return job; }
  cancelJob(jobId, creatorId) { const job=this.jobs.get(jobId); assert(job,'job not found'); assert(job.creatorId===creatorId,'only creator may cancel'); assert(job.status==='OPEN','only open jobs may be cancelled'); job.status='CANCELLED'; job.updatedAt=now(); this.event('JOB_CANCELLED',{jobId}); return job; }
  createService(input) { assert(this.agents.has(input.ownerAgentId),'valid ownerAgentId required'); const service={id:id('svc'),name:input.name,description:input.description,ownerAgentId:input.ownerAgentId,capabilityChain:input.capabilityChain??[],createdAt:now()}; this.services.set(service.id,service); return service; }
  postLoungeMessage({agentId,message,type='discussion'}) { assert(this.loungeEnabled,'lounge disabled'); assert(this.agents.has(agentId),'agent not found'); const item={id:id('msg'),agentId,type,message:String(message).slice(0,1000),at:now()}; this.lounge.push(item); return item; }
  stats() { const jobs=[...this.jobs.values()]; const paid=jobs.filter(j=>j.status==='PAID'); const agentCreated=jobs.filter(j=>j.creatorType==='agent'); const repeats=new Map(); for(const tx of this.transactions){const k=`${tx.payer}->${tx.payee}`; repeats.set(k,(repeats.get(k)||0)+1);} return {activeAgents:[...this.agents.values()].filter(a=>a.status==='ACTIVE').length,activeJobs:jobs.filter(j=>['OPEN','CLAIMED','IN_PROGRESS','SUBMITTED','VERIFYING'].includes(j.status)).length,jobsCreated:jobs.length,jobsCompleted:paid.length,agentCreatedJobs:agentCreated.length,agentToAgentTransactions:this.transactions.length,transactionVolume:this.transactions.reduce((s,t)=>s+Number(t.amount),0),services:this.services.size,successRate:jobs.length?paid.length/jobs.length:0,repeatTransactions:[...repeats.values()].filter(n=>n>1).reduce((s,n)=>s+n-1,0)}; }
  activity() { return this.events.slice(-100); }
  graph() { return { nodes:[...this.agents.values()].map(a=>({id:a.id,type:'agent',label:a.name})).concat([...this.jobs.values()].map(j=>({id:j.id,type:'job',label:j.title})),this.transactions.map(t=>({id:t.id,type:'transaction',label:`${t.amount} ${t.asset}`}))), edges:[...this.jobs.values()].flatMap(j=>[{from:j.creatorId,to:j.id,type:'created'},...(j.workerId?[{from:j.id,to:j.workerId,type:'worked_by'}]:[]),...(j.parentJobId?[{from:j.parentJobId,to:j.id,type:'spawned'}]:[])]).concat(this.transactions.flatMap(t=>[{from:t.payer,to:t.id,type:'paid'},{from:t.id,to:t.payee,type:'received'}])) }; }
  getAgentCard(agentId, baseUrl) { const agent=this.agents.get(agentId); assert(agent,'agent not found'); return agentCard(agent,baseUrl); }
}
