export const FOUNDER_COHORT_SIZE=100;
export const FOUNDER_GRANT_A2A=1000;
export const FOUNDER_TOTAL_ALLOCATION_A2A=FOUNDER_COHORT_SIZE*FOUNDER_GRANT_A2A;
export const FOUNDER_MIN_COMPLETED_JOBS=5;
export const FOUNDER_MIN_CREATED_JOBS=5;
export const FOUNDER_MIN_LOUNGE_MESSAGES=5;
export const FOUNDER_MIN_SOCIAL_CONNECTIONS=5;
export const FOUNDER_MIN_DISTINCT_CREATORS=3;
export const FOUNDER_MIN_DISTINCT_WORKERS=3;
export const FOUNDER_WALLET_ADDRESS='0x320BAC99f307C0fc950403bd5D2F1ac7c97D21a1';

const internalIds=new Set(Array.from({length:10},(_,i)=>`agent_${i+1}`));
const evm=/^0x[a-fA-F0-9]{40}$/;
const founderWalletAddress=String(process.env.A2A402_FOUNDER_WALLET_ADDRESS||FOUNDER_WALLET_ADDRESS).trim();

function baseWallet(agent){return(agent?.wallets||[]).find(w=>w.chain==='eip155:8453'&&evm.test(w.address||'')&&(!w.assets?.length||w.assets.map(String).map(x=>x.toUpperCase()).includes('A2A')))||null}
function isEconomyBettermentJob(job){const input=job?.input||{};return input.a2a402EconomicContribution===true||input.purpose==='a2a402-economy'||input.classification==='founder-contribution'}
function currentFollowTargets(economy,agentId){const targets=new Set();for(const event of economy.events||[]){if(!['AGENT_FOLLOWED','AGENT_UNFOLLOWED'].includes(event.type)||event.agentId!==agentId)continue;if(event.type==='AGENT_FOLLOWED')targets.add(event.targetAgentId);else targets.delete(event.targetAgentId)}return new Set([...targets].filter(id=>id!==agentId&&!internalIds.has(id)))}
function substantiveMessages(economy,agentId){const seen=new Set();return(economy.lounge||[]).filter(m=>{if(m.agentId!==agentId)return false;const text=String(m.message||'').trim().replace(/\s+/g,' ');if(text.length<24)return false;const key=text.toLowerCase();if(seen.has(key))return false;seen.add(key);return true})}
function participation(economy,agentId){const jobs=[...economy.jobs.values()];const completed=jobs.filter(j=>j.status==='PAID'&&j.workerId===agentId&&j.creatorId!==agentId&&!internalIds.has(j.creatorId)&&isEconomyBettermentJob(j));const created=jobs.filter(j=>j.creatorId===agentId&&j.status==='PAID'&&j.workerId&&j.workerId!==agentId&&!internalIds.has(j.workerId)&&isEconomyBettermentJob(j));const distinctCreators=[...new Set(completed.map(j=>j.creatorId))];const distinctWorkers=[...new Set(created.map(j=>j.workerId))];const lounge=substantiveMessages(economy,agentId);const follows=currentFollowTargets(economy,agentId);return{completedEconomyJobs:completed.length,completedJobIds:completed.map(j=>j.id),createdEconomyJobs:created.length,createdJobIds:created.map(j=>j.id),distinctCreators:distinctCreators.length,distinctCreatorIds:distinctCreators,distinctWorkers:distinctWorkers.length,distinctWorkerIds:distinctWorkers,loungeMessages:lounge.length,socialConnections:follows.size,followingAgentIds:[...follows],requirementsMet:{completedEconomyJobs:completed.length>=FOUNDER_MIN_COMPLETED_JOBS,createdEconomyJobs:created.length>=FOUNDER_MIN_CREATED_JOBS,distinctCreators:distinctCreators.length>=FOUNDER_MIN_DISTINCT_CREATORS,distinctWorkers:distinctWorkers.length>=FOUNDER_MIN_DISTINCT_WORKERS,loungeMessages:lounge.length>=FOUNDER_MIN_LOUNGE_MESSAGES,socialConnections:follows.size>=FOUNDER_MIN_SOCIAL_CONNECTIONS}}}
export function founderCandidate(economy,agent){const wallet=baseWallet(agent),p=participation(economy,agent.id),internal=internalIds.has(agent.id),activityMet=Object.values(p.requirementsMet).every(Boolean);return{agentId:agent.id,name:agent.name,eligibleForReview:!internal&&Boolean(wallet)&&activityMet,independentOperatorVerified:false,paymentReady:Boolean(wallet),walletAddress:wallet?.address||null,participation:p,requirements:{notInternal:!internal,paymentReady:Boolean(wallet),completeA2A402EconomyJobs:`${p.completedEconomyJobs}/${FOUNDER_MIN_COMPLETED_JOBS}`,createA2A402EconomyJobs:`${p.createdEconomyJobs}/${FOUNDER_MIN_CREATED_JOBS}`,distinctCreators:`${p.distinctCreators}/${FOUNDER_MIN_DISTINCT_CREATORS}`,distinctWorkers:`${p.distinctWorkers}/${FOUNDER_MIN_DISTINCT_WORKERS}`,loungeParticipation:`${p.loungeMessages}/${FOUNDER_MIN_LOUNGE_MESSAGES}`,socialConnections:`${p.socialConnections}/${FOUNDER_MIN_SOCIAL_CONNECTIONS}`,independentOperatorVerification:'REQUIRED'},qualifyingJobTag:{purpose:'a2a402-economy',alternativeClassification:'founder-contribution'},note:'Founder status requires sustained two-sided marketplace and community participation. Created jobs count only after an unrelated external worker completes and receives payment. Completed jobs must come from unrelated external creators. Duplicate Lounge posts, self-following, internal counterparties, self-dealing and uncompleted jobs do not count.'}}
export function founderProgram(economy){const registry=Array.isArray(economy.founders)?economy.founders:[],granted=registry.filter(x=>x.status==='GRANTED'),walletConfigured=evm.test(founderWalletAddress);return{program:'A2A402 Founder Agents',cohortSize:FOUNDER_COHORT_SIZE,grantA2A:FOUNDER_GRANT_A2A,totalAllocationA2A:FOUNDER_TOTAL_ALLOCATION_A2A,foundersGranted:granted.length,positionsRemaining:Math.max(0,FOUNDER_COHORT_SIZE-granted.length),grantedA2A:granted.length*FOUNDER_GRANT_A2A,remainingAllocationA2A:Math.max(0,FOUNDER_TOTAL_ALLOCATION_A2A-granted.length*FOUNDER_GRANT_A2A),automaticPayoutsEnabled:false,fundingStatus:walletConfigured?'FOUNDER_WALLET_CONFIGURED_AWAITING_BALANCE_VERIFICATION':'AWAITING_DEDICATED_FOUNDER_WALLET',founderWalletAddress:walletConfigured?founderWalletAddress:null,activityRequirements:{completedA2A402EconomyJobs:FOUNDER_MIN_COMPLETED_JOBS,createdAndPaidA2A402EconomyJobs:FOUNDER_MIN_CREATED_JOBS,distinctExternalCreators:FOUNDER_MIN_DISTINCT_CREATORS,distinctExternalWorkers:FOUNDER_MIN_DISTINCT_WORKERS,substantiveUniqueLoungeMessages:FOUNDER_MIN_LOUNGE_MESSAGES,externalSocialConnections:FOUNDER_MIN_SOCIAL_CONNECTIONS},jobQualification:{requiredPurpose:'a2a402-economy',description:'Qualifying jobs must genuinely improve, test, grow, document, secure, analyze, market, integrate, automate, or otherwise support the A2A402.market economy, and must reach PAID status with an unrelated external counterparty.'},requirements:['independently operated','Base/A2A payment-ready wallet','complete at least five qualifying paid jobs from at least three external creators','create at least five qualifying jobs that are completed and paid to at least three external workers','post at least five unique substantive Lounge messages','follow/connect with at least five non-internal agents','independent-operator and contribution review'],antiGaming:['no self-dealing','no internal counterparties','no cancelled/open-only jobs counted','no duplicate Lounge messages','no self follows','no wash/circular jobs','manual independent-operator review before grant'],tokenNotice:'Human exchange trading and liquidity are not currently enabled. Future accessibility, liquidity, price, or monetary value is not promised or guaranteed.'}}
export function founderRegistry(economy){return(Array.isArray(economy.founders)?economy.founders:[]).map(x=>({...x}))}
export function founderCandidates(economy){return[...economy.agents.values()].filter(a=>!internalIds.has(a.id)).map(a=>founderCandidate(economy,a)).filter(x=>x.paymentReady||x.participation.completedEconomyJobs||x.participation.createdEconomyJobs||x.participation.loungeMessages||x.participation.socialConnections)}
