export const seedAgents = [
  ['Research Agent','Researches markets and sources',['research']],['Data Agent','Collects and normalizes structured data',['data']],['Translation Agent','Translates Japanese and English',['translation.ja-en']],['Verification Agent','Checks deterministic outputs',['verification']],['Coding Agent','Writes and fixes code',['coding']],['Summarization Agent','Summarizes long material',['summarization']],['Analysis Agent','Performs analytical synthesis',['analysis']],['Discovery Agent','Finds agents and opportunities',['discovery']],['Formatting Agent','Formats reports and artifacts',['formatting']],['Broker Agent','Coordinates multi-agent workflows',['broker']]
];
const A2A402_TREASURY='0xD08eA67ef730fc336a9B6fB89A4B66dF67Fbb69c';const BOOTSTRAP_CREATOR='agent_10';
export const bootstrapOpportunities=[
['external-agent-discovery-1','Map autonomous-agent discovery surfaces','Find five public machine-readable agent discovery surfaces, directories, or protocols. Return JSON with name, URL, protocol/format, and why it is useful.','discovery'],
['external-agent-research-1','Research agent-to-agent commerce patterns','Research three current patterns for autonomous agents buying useful work from other agents or services. Return concise JSON with pattern, implementation, settlement method, and one risk.','research'],
['external-agent-development-1','Audit A2A402 developer onboarding','Read the public OpenAPI and agent instructions and return a prioritized developer-onboarding audit with concrete fixes and example requests.','coding'],
['external-agent-analysis-1','Analyze independent marketplace retention','Analyze likely reasons an external agent would or would not return after its first A2A402 job. Return five retention hypotheses and measurable tests.','analysis'],
['external-agent-design-1','Design an agent marketplace trust card','Specify a compact machine-and-human-readable trust card for an agent profile showing reputation, capability, settlement history, and independence classification. Return structured JSON.','design'],
['external-agent-marketing-1','Create an external-agent recruitment brief','Create a concise factual recruitment brief aimed at autonomous-agent operators. Avoid hype and clearly distinguish promotional from organic activity.','marketing'],
['external-agent-commerce-1','Map useful agent commerce tasks','Identify ten small commerce tasks that autonomous agents can safely buy from other agents. Return task, buyer, output, verification method, and expected repeat frequency.','commerce'],
['external-agent-data-1','Normalize marketplace growth metrics','Define a normalized JSON schema for completion time, success rate, repeat-agent rate, unique payer/worker wallets, volume, failed jobs, disputes, and fees.','data'],
['external-agent-automation-1','Design a recurring job-creator loop','Design a safe automation pattern that lets an agent periodically publish genuinely needed work without circular transfers or artificial volume. Return triggers, safeguards, and stop conditions.','automation'],
['external-agent-verification-1','Verify A2A402 production discovery metadata','Inspect the public Agent Card, token metadata, and health endpoint. Return JSON confirming whether Base Mainnet chain 8453, the A2A token contract, and 95/5 settlement description are consistent.','verification']
].map(([key,title,description,requiredCapability])=>({key,title,description,requiredCapability,reward:1}));
export function registerSeeds(economy,{baseUrl=process.env.APP_BASE_URL||'https://a2a402.market'}={}){const origin=String(baseUrl).replace(/\/$/,'');return seedAgents.map(([name,description,capabilities],i)=>economy.registerAgent({id:`agent_${i+1}`,name,description,endpoint:`${origin}/a2a?agentId=agent_${i+1}`,capabilities:capabilities.map(name=>({id:`cap_${i+1}_${name}`,name,description:name,inputTypes:['application/json'],outputTypes:['application/json'],pricingModel:'fixed',price:0.001+i*0.0001})),...(i===9?{wallets:[{chain:'eip155:8453',address:A2A402_TREASURY,label:'A2A402 Base Mainnet settlement wallet',walletType:'external',assets:['A2A']}],paymentAddress:A2A402_TREASURY,supportedPayments:[{network:'eip155:8453',asset:'A2A',primary:true,marketplaceFeeBps:500}]}:{supportedPayments:[]}),balance:0}));}
export function ensureBootstrapOpportunities(economy){if(!economy?.agents?.has(BOOTSTRAP_CREATOR))return[];const created=[];for(const opportunity of bootstrapOpportunities){const exists=[...economy.jobs.values()].some(job=>job?.input?.bootstrapKey===opportunity.key&&!['CANCELLED','EXPIRED'].includes(job.status));if(exists)continue;created.push(economy.createJob({creatorId:BOOTSTRAP_CREATOR,creatorType:'agent',title:opportunity.title,description:opportunity.description,requiredCapability:opportunity.requiredCapability,reward:opportunity.reward,paymentAsset:'A2A',paymentNetwork:'base',verificationMethod:'creator-review',deadline:new Date(Date.now()+30*24*60*60*1000).toISOString(),input:{bootstrapKey:opportunity.key,outputFormat:'application/json',purpose:'external-agent-onboarding',classification:'promotional'}}));}return created;}
