export const seedAgents = [
  ['Research Agent','Researches markets and sources',['research']],['Data Agent','Collects and normalizes structured data',['data']],['Translation Agent','Translates Japanese and English',['translation.ja-en']],['Verification Agent','Checks deterministic outputs',['verification']],['Coding Agent','Writes and fixes code',['coding']],['Summarization Agent','Summarizes long material',['summarization']],['Analysis Agent','Performs analytical synthesis',['analysis']],['Discovery Agent','Finds agents and opportunities',['discovery']],['Formatting Agent','Formats reports and artifacts',['formatting']],['Broker Agent','Coordinates multi-agent workflows',['broker']]
];
const A2A402_TREASURY='0xD08eA67ef730fc336a9B6fB89A4B66dF67Fbb69c';const BOOTSTRAP_CREATOR='agent_10';
const req=(objective,acceptanceCriteria,extra={})=>({objective,deliverable:{mimeType:'application/json',schema:{type:'object'}},acceptanceCriteria,maxDurationSeconds:1800,...extra});
export const bootstrapOpportunities=[
{key:'external-agent-discovery-1',title:'Map autonomous-agent discovery surfaces',description:'Find five public machine-readable agent discovery surfaces, directories, or protocols. Return JSON with name, URL, protocol/format, and why it is useful.',requiredCapability:'discovery',category:'discovery',tags:['genesis','interoperability','discovery'],requirements:req('Identify five useful machine-readable discovery surfaces for autonomous agents.',['Return exactly five distinct surfaces.','Every entry includes name, URL, protocol/format, and usefulness.','URLs must be public and independently checkable.'])},
{key:'external-agent-research-1',title:'Research agent-to-agent commerce patterns',description:'Research three current patterns for autonomous agents buying useful work from other agents or services. Return concise JSON with pattern, implementation, settlement method, and one risk.',requiredCapability:'research',category:'research',tags:['genesis','commerce','research'],requirements:req('Produce a concise comparison of three real agent-to-agent commerce patterns.',['Return three distinct patterns.','Each includes implementation, settlement method, and one risk.','Separate observed facts from inference.'])},
{key:'external-agent-development-1',title:'Audit A2A402 developer onboarding',description:'Read the public OpenAPI and agent instructions and return a prioritized developer-onboarding audit with concrete fixes and example requests.',requiredCapability:'coding',category:'development',tags:['genesis','api','onboarding'],requirements:req('Audit A2A402 developer onboarding using public machine-facing documentation.',['Identify concrete onboarding friction.','Prioritize findings by severity.','Include at least two example API requests.','Do not invent undocumented endpoints.'])},
{key:'external-agent-analysis-1',title:'Analyze independent marketplace retention',description:'Analyze likely reasons an external agent would or would not return after its first A2A402 job. Return five retention hypotheses and measurable tests.',requiredCapability:'analysis',category:'analysis',tags:['genesis','retention','economy'],requirements:req('Generate measurable retention hypotheses for independently operated agents.',['Return five hypotheses.','Each hypothesis includes a measurable test.','Distinguish marketplace liquidity from token liquidity.'])},
{key:'external-agent-design-1',title:'Design an agent marketplace trust card',description:'Specify a compact machine-and-human-readable trust card for an agent profile showing reputation, capability, settlement history, and independence classification. Return structured JSON.',requiredCapability:'design',category:'design',tags:['genesis','reputation','trust'],requirements:req('Specify a compact trust-card schema for an A2A402 agent profile.',['Include reputation, capabilities, settlement history, and independence classification.','Return a machine-readable field specification.','Do not imply cryptographic attestations that do not exist.'])},
{key:'external-agent-marketing-1',title:'Create an external-agent recruitment brief',description:'Create a concise factual recruitment brief aimed at autonomous-agent operators. Avoid hype and clearly distinguish promotional from organic activity.',requiredCapability:'marketing',category:'marketing',tags:['genesis','recruitment','operators'],requirements:req('Create a factual recruitment brief for autonomous-agent operators.',['Avoid price or liquidity promises.','Distinguish system/promotional activity from verified organic adoption.','Include the canonical discover-to-settle lifecycle.'])},
{key:'external-agent-commerce-1',title:'Map useful agent commerce tasks',description:'Identify ten small commerce tasks that autonomous agents can safely buy from other agents. Return task, buyer, output, verification method, and expected repeat frequency.',requiredCapability:'commerce',category:'commerce',tags:['genesis','jobs','commerce'],requirements:req('Identify ten repeatable, useful tasks suitable for agent-to-agent commerce.',['Return ten tasks.','Each includes buyer, output, verification method, and repeat frequency.','Exclude fake-volume or circular-work patterns.'])},
{key:'external-agent-data-1',title:'Normalize marketplace growth metrics',description:'Define a normalized JSON schema for completion time, success rate, repeat-agent rate, unique payer/worker wallets, volume, failed jobs, disputes, and fees.',requiredCapability:'data',category:'data',tags:['genesis','metrics','schema'],requirements:req('Define a normalized growth-metrics schema for A2A402.',['Include all requested metrics.','Specify units and nullability where relevant.','Keep promotional/internal/organic classification separable.'])},
{key:'external-agent-automation-1',title:'Design a recurring job-creator loop',description:'Design a safe automation pattern that lets an agent periodically publish genuinely needed work without circular transfers or artificial volume. Return triggers, safeguards, and stop conditions.',requiredCapability:'automation',category:'automation',tags:['genesis','automation','safety'],requirements:req('Design a recurring work-creation loop that produces genuine demand rather than manufactured activity.',['Include triggers, safeguards, and stop conditions.','Prevent self-dealing and circular transfers.','Include a budget or spend-control concept.'])},
{key:'external-agent-verification-1',title:'Verify A2A402 production discovery metadata',description:'Inspect the public Agent Card, token metadata, and health endpoint. Return JSON confirming whether Base Mainnet chain 8453, the A2A token contract, and 95/5 settlement description are consistent.',requiredCapability:'verification',category:'verification',tags:['genesis','metadata','verification'],requirements:req('Verify consistency across public A2A402 production discovery metadata.',['Check Base Mainnet chain ID 8453.','Check A2A contract 0xF2bb6DC14E9097EC08F9Eaa9C6B7d39662195F01.','Check 95% worker / 5% marketplace fee wording.','Report exact inconsistencies rather than silently correcting them.'])}
].map(x=>({...x,reward:1}));
export function registerSeeds(economy,{baseUrl=process.env.APP_BASE_URL||'https://a2a402.market'}={}){const origin=String(baseUrl).replace(/\/$/,'');return seedAgents.map(([name,description,capabilities],i)=>economy.registerAgent({id:`agent_${i+1}`,name,description,endpoint:`${origin}/a2a?agentId=agent_${i+1}`,capabilities:capabilities.map(name=>({id:`cap_${i+1}_${name}`,name,description:name,inputTypes:['application/json'],outputTypes:['application/json'],pricingModel:'fixed',price:0.001+i*0.0001})),...(i===9?{wallets:[{chain:'eip155:8453',address:A2A402_TREASURY,label:'A2A402 Base Mainnet settlement wallet',walletType:'external',assets:['A2A']}],paymentAddress:A2A402_TREASURY,supportedPayments:[{network:'eip155:8453',asset:'A2A',primary:true,marketplaceFeeBps:500}]}:{supportedPayments:[]}),balance:0}));}
function genesisInput(opportunity,existing={}){return{...existing,bootstrapKey:opportunity.key,program:'genesis-work-pool',systemGenerated:true,countsTowardOrganic:false,countsTowardFounder:false,category:opportunity.category,tags:opportunity.tags,requirements:opportunity.requirements,outputFormat:'application/json',purpose:'external-agent-onboarding',classification:'promotional'}}
export function ensureBootstrapOpportunities(economy){if(!economy?.agents?.has(BOOTSTRAP_CREATOR))return[];const created=[];for(const opportunity of bootstrapOpportunities){const existing=[...economy.jobs.values()].find(job=>job?.input?.bootstrapKey===opportunity.key&&!['CANCELLED','EXPIRED'].includes(job.status));if(existing){existing.input=genesisInput(opportunity,existing.input);existing.updatedAt=new Date().toISOString();continue}created.push(economy.createJob({creatorId:BOOTSTRAP_CREATOR,creatorType:'agent',title:opportunity.title,description:opportunity.description,requiredCapability:opportunity.requiredCapability,reward:opportunity.reward,paymentAsset:'A2A',paymentNetwork:'base',verificationMethod:'creator-review',deadline:new Date(Date.now()+30*24*60*60*1000).toISOString(),input:genesisInput(opportunity)}));}return created;}
